import unittest
import requests
from ddt import ddt, file_data
from nose.tools import assert_equal

TENON_URL = 'http://beta.tenon.io/api/'
API_KEY = 'foo'

@ddt
class TestAccessibility(unittest.TestCase):
    """
    Test the results generated by Tenon IO
    """

    @file_data('data.json')
    def test_score(self, data):
        """
        Test accessibility score reported from Tenon.io.
        """
        url = data.get('url')
        params = {'key': API_KEY, 'url': url}
        resp = requests.post(TENON_URL, data=params)
        assert_equal(resp.status_code, 200)

        result = resp.json()
        assert_equal(result.get('status'), 200)

        summary = result.get('resultSummary')
        assert summary

        grade = summary.get('letterGrade')
        assert_equal(grade, data.get('grade'))

        issues = summary.get('issues')
        for k, v in issues.iteritems():
            assert v <= data.get(k)

if __name__ == '__main__':
    unittest.main()
