import unittest
from bok_choy.web_app_test import WebAppTest
from pages import TenonIoTestNowPage
from pdb import set_trace

BASE_URL = 'https://www.google.com'

class TestTenon(WebAppTest):
    """
    Test the results generated by Tenon IO
    """

    def test_score(self):
        """
        Make sure that the page is accessible.
        """
        test_now = TenonIoTestNowPage(self.browser)
        test_now.visit()

        test_now.submit_data(BASE_URL)
        score = test_now.get_score()

        assert score.get('total') == '11'
        assert score.get('errors') == '9'
        assert score.get('warnings') == '2'



if __name__ == '__main__':
    unittest.main()
