import unittest
from bok_choy.web_app_test import WebAppTest
from pages import TenonIoTestNowPage
from pdb import set_trace
from ddt import ddt, file_data
from nose.tools import assert_equal

BASE_URL = 'https://www.google.com'

@ddt
class TestAccessibility(WebAppTest):
    """
    Test the results generated by Tenon IO
    """

    @file_data('data.json')
    def test_score(self, data):
        """
        Test accessibility score reported from Tenon.io.
        """
        test_now = TenonIoTestNowPage(self.browser)
        test_now.visit()

        test_now.submit_data(data.get('url'))
        score = test_now.get_score()

        assert_equal(int(score.get('total')), data.get('total'))
        assert_equal(int(score.get('errors')), data.get('errors'))
        assert_equal(int(score.get('warnings')), data.get('warnings'))


if __name__ == '__main__':
    unittest.main()
